# modules/rancher/main.tf
# Deploys cert-manager and Rancher onto the k3s cluster using Helm.
# A private CA is generated by Terraform (tls provider) and stored in
# a Kubernetes Secret. cert-manager issues Rancher's TLS certificate
# from that CA via a ClusterIssuer.
#
# Access Rancher after apply:
#   kubectl port-forward -n cattle-system svc/rancher 8443:443
#   Browse: https://rancher.local:8443  (add to /etc/hosts)

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.13"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.30"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

# ---------------------------------------------------------------------------
# Private CA — generated once, stored in tfstate (sensitive)
# ---------------------------------------------------------------------------
resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem   = tls_private_key.ca.private_key_pem
  is_ca_certificate = true

  subject {
    common_name         = "Whitley Private CA"
    organization        = "Whitley Homelab"
    organizational_unit = "Infrastructure"
  }

  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "digital_signature",
  ]
}

# ---------------------------------------------------------------------------
# cert-manager namespace + Helm release
# ---------------------------------------------------------------------------
resource "kubernetes_namespace" "cert_manager" {
  metadata {
    name = "cert-manager"
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }
}

resource "helm_release" "cert_manager" {
  depends_on = [kubernetes_namespace.cert_manager]

  name       = "cert-manager"
  repository = "https://charts.jetstack.io"
  chart      = "cert-manager"
  version    = var.cert_manager_chart_version
  namespace  = kubernetes_namespace.cert_manager.metadata[0].name

  # Install CRDs as part of the Helm release so they are lifecycle-managed
  set {
    name  = "installCRDs"
    value = "true"
  }

  # Disable the default self-signed issuer — we supply our own CA
  set {
    name  = "ingressShim.defaultIssuerName"
    value = "private-ca-issuer"
  }

  set {
    name  = "ingressShim.defaultIssuerKind"
    value = "ClusterIssuer"
  }

  wait    = true
  timeout = 300
}

# ---------------------------------------------------------------------------
# cattle-system namespace
# ---------------------------------------------------------------------------
resource "kubernetes_namespace" "cattle_system" {
  metadata {
    name = "cattle-system"
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }
}

# ---------------------------------------------------------------------------
# Kubernetes Secret — private CA cert + key for cert-manager
# Must live in cert-manager namespace for the ClusterIssuer to reference it.
# ---------------------------------------------------------------------------
resource "kubernetes_secret" "ca_key_pair" {
  depends_on = [
    kubernetes_namespace.cert_manager,
    helm_release.cert_manager,
  ]

  metadata {
    name      = "whitley-ca-key-pair"
    namespace = kubernetes_namespace.cert_manager.metadata[0].name
  }

  type = "kubernetes.io/tls"

  data = {
    "tls.crt" = tls_self_signed_cert.ca.cert_pem
    "tls.key" = tls_private_key.ca.private_key_pem
  }
}

# ---------------------------------------------------------------------------
# ClusterIssuer — uses the private CA secret above
# ---------------------------------------------------------------------------
resource "kubernetes_manifest" "cluster_issuer" {
  depends_on = [
    helm_release.cert_manager,
    kubernetes_secret.ca_key_pair,
  ]

  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "ClusterIssuer"
    metadata = {
      name = "private-ca-issuer"
    }
    spec = {
      ca = {
        secretName = kubernetes_secret.ca_key_pair.metadata[0].name
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Rancher Helm release
# ---------------------------------------------------------------------------
resource "helm_release" "rancher" {
  depends_on = [
    kubernetes_namespace.cattle_system,
    kubernetes_manifest.cluster_issuer,
  ]

  name       = "rancher"
  repository = "https://releases.rancher.com/server-charts/stable"
  chart      = "rancher"
  version    = var.rancher_chart_version
  namespace  = kubernetes_namespace.cattle_system.metadata[0].name

  # Internal-only hostname — add to /etc/hosts on any machine that needs access
  set {
    name  = "hostname"
    value = var.rancher_hostname
  }

  # Single replica — non-HA home-lab setup
  set {
    name  = "replicas"
    value = "1"
  }

  # Use our cert-manager ClusterIssuer for TLS
  set {
    name  = "ingress.tls.source"
    value = "secret"
  }

  # Tells Rancher to trust the private CA when making internal API calls
  set {
    name  = "privateCA"
    value = "true"
  }

  # ClusterIP — no LoadBalancer, no NodePort, no public exposure.
  # Access via: kubectl port-forward -n cattle-system svc/rancher 8443:443
  set {
    name  = "service.type"
    value = "ClusterIP"
  }

  # Required on k3s 1.25+ (PSP removed)
  set {
    name  = "global.cattle.pspEnabled"
    value = "false"
  }

  # Annotate the ingress so cert-manager issues a cert signed by our CA
  set {
    name  = "ingress.extraAnnotations.cert-manager\\.io/cluster-issuer"
    value = "private-ca-issuer"
  }

  wait    = true
  timeout = 600
}
