# modules/rancher/main.tf
# Deploys cert-manager and Rancher onto the k3s cluster using Helm.
# A private CA is generated by Terraform (tls provider) and stored in
# a Kubernetes Secret. cert-manager issues Rancher's TLS certificate
# from that CA via a ClusterIssuer.
#
# Access Rancher after apply:
#   kubectl port-forward -n cattle-system svc/rancher 8443:443
#   Browse: https://rancher.local:8443  (add to /etc/hosts)

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.13"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.30"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

# ---------------------------------------------------------------------------
# Private CA — generated once, stored in tfstate (sensitive)
# ---------------------------------------------------------------------------
resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem   = tls_private_key.ca.private_key_pem
  is_ca_certificate = true

  subject {
    common_name         = "Whitley Private CA"
    organization        = "Whitley Homelab"
    organizational_unit = "Infrastructure"
  }

  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "digital_signature",
  ]
}

# ---------------------------------------------------------------------------
# cert-manager namespace + Helm release
# ---------------------------------------------------------------------------
resource "kubernetes_namespace" "cert_manager" {
  metadata {
    name = "cert-manager"
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }
}

resource "helm_release" "cert_manager" {
  depends_on = [kubernetes_namespace.cert_manager]

  name       = "cert-manager"
  repository = "https://charts.jetstack.io"
  chart      = "cert-manager"
  version    = var.cert_manager_chart_version
  namespace  = kubernetes_namespace.cert_manager.metadata[0].name

  # Install CRDs as part of the Helm release so they are lifecycle-managed
  set {
    name  = "installCRDs"
    value = "true"
  }

  # Disable the default self-signed issuer — we supply our own CA
  set {
    name  = "ingressShim.defaultIssuerName"
    value = "private-ca-issuer"
  }

  set {
    name  = "ingressShim.defaultIssuerKind"
    value = "ClusterIssuer"
  }

  wait    = true
  timeout = 300
}

# ---------------------------------------------------------------------------
# cattle-system namespace
# ---------------------------------------------------------------------------
resource "kubernetes_namespace" "cattle_system" {
  metadata {
    name = "cattle-system"
    labels = {
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }
}

# ---------------------------------------------------------------------------
# tls-ca secret — required by Rancher when privateCA=true.
# Rancher mounts this secret to trust the private CA for internal API calls.
# Must be named "tls-ca" in cattle-system with key "cacerts.pem".
# ---------------------------------------------------------------------------
resource "kubernetes_secret" "tls_ca" {
  depends_on = [kubernetes_namespace.cattle_system]

  metadata {
    name      = "tls-ca"
    namespace = kubernetes_namespace.cattle_system.metadata[0].name
  }

  data = {
    "cacerts.pem" = tls_self_signed_cert.ca.cert_pem
  }
}

# ---------------------------------------------------------------------------
# Wait for cert-manager CRDs to be fully established in the API server.
# helm_release wait=true only confirms pods are Running; it does not guarantee
# the CRDs (ClusterIssuer, Certificate, etc.) are registered and queryable.
# ---------------------------------------------------------------------------
resource "null_resource" "wait_for_cert_manager_crds" {
  depends_on = [helm_release.cert_manager]

  provisioner "local-exec" {
    command = <<-EOT
      echo "Waiting for cert-manager CRDs to be established..."
      for i in $(seq 1 30); do
        kubectl --kubeconfig=${var.kubeconfig_path} \
          get crd clusterissuers.cert-manager.io >/dev/null 2>&1 && \
        kubectl --kubeconfig=${var.kubeconfig_path} \
          wait --for=condition=Established \
          crd/clusterissuers.cert-manager.io --timeout=60s && \
        echo "CRDs ready." && exit 0
        echo "Attempt $i: CRDs not ready yet, retrying in 5s..."
        sleep 5
      done
      echo "Timed out waiting for cert-manager CRDs." && exit 1
    EOT
  }
}

# ---------------------------------------------------------------------------
# Kubernetes Secret — private CA cert + key for cert-manager
# Must live in cert-manager namespace for the ClusterIssuer to reference it.
# ---------------------------------------------------------------------------
resource "kubernetes_secret" "ca_key_pair" {
  depends_on = [
    kubernetes_namespace.cert_manager,
    null_resource.wait_for_cert_manager_crds,
  ]

  metadata {
    name      = "whitley-ca-key-pair"
    namespace = kubernetes_namespace.cert_manager.metadata[0].name
  }

  type = "kubernetes.io/tls"

  data = {
    "tls.crt" = tls_self_signed_cert.ca.cert_pem
    "tls.key" = tls_private_key.ca.private_key_pem
  }
}

# ---------------------------------------------------------------------------
# ClusterIssuer — uses the private CA secret above.
# Applied via kubectl local-exec to avoid kubernetes_manifest plan-time CRD
# validation, which fails when the CRD does not yet exist in the API server.
# ---------------------------------------------------------------------------
resource "null_resource" "cluster_issuer" {
  depends_on = [
    null_resource.wait_for_cert_manager_crds,
    kubernetes_secret.ca_key_pair,
  ]

  triggers = {
    kubeconfig_path = var.kubeconfig_path
  }

  provisioner "local-exec" {
    command = <<-EOT
      kubectl --kubeconfig=${var.kubeconfig_path} apply -f - <<EOF
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: private-ca-issuer
      spec:
        ca:
          secretName: ${kubernetes_secret.ca_key_pair.metadata[0].name}
      EOF
    EOT
  }

  provisioner "local-exec" {
    when    = destroy
    command = "kubectl --kubeconfig=${self.triggers.kubeconfig_path} delete clusterissuer private-ca-issuer --ignore-not-found || true"
    on_failure = continue
  }
}

# ---------------------------------------------------------------------------
# Stale API service cleanup — runs on destroy before namespace deletion.
# Rancher registers ext.cattle.io/v1 with the aggregation layer. After the
# Helm release is removed the APIService object becomes stale, causing
# namespace deletion to fail with DiscoveryFailed. This resource removes
# those stale APIServices so the namespaces can be cleanly deleted.
# ---------------------------------------------------------------------------
resource "null_resource" "rancher_api_cleanup" {
  triggers = {
    kubeconfig_path = var.kubeconfig_path
  }

  provisioner "local-exec" {
    when    = destroy
    command = <<-EOT
      kubectl --kubeconfig=${self.triggers.kubeconfig_path} \
        delete apiservice v1.ext.cattle.io --ignore-not-found || true
      kubectl --kubeconfig=${self.triggers.kubeconfig_path} \
        get apiservice -o name | grep cattle.io | \
        xargs -r kubectl --kubeconfig=${self.triggers.kubeconfig_path} delete --ignore-not-found || true
    EOT
    on_failure = continue
  }
}

# ---------------------------------------------------------------------------
# Rancher Helm release
# ---------------------------------------------------------------------------
resource "helm_release" "rancher" {
  depends_on = [
    kubernetes_namespace.cattle_system,
    null_resource.cluster_issuer,
    kubernetes_secret.tls_ca,
    null_resource.rancher_api_cleanup,
  ]

  name       = "rancher"
  repository = "https://releases.rancher.com/server-charts/stable"
  chart      = "rancher"
  version    = var.rancher_chart_version
  namespace  = kubernetes_namespace.cattle_system.metadata[0].name

  # Internal-only hostname — add to /etc/hosts on any machine that needs access
  set {
    name  = "hostname"
    value = var.rancher_hostname
  }

  # Single replica — non-HA home-lab setup
  set {
    name  = "replicas"
    value = "1"
  }

  # Use our cert-manager ClusterIssuer for TLS
  set {
    name  = "ingress.tls.source"
    value = "secret"
  }

  # Tells Rancher to trust the private CA when making internal API calls
  set {
    name  = "privateCA"
    value = "true"
  }

  # ClusterIP — no LoadBalancer, no NodePort, no public exposure.
  # Access via: kubectl port-forward -n cattle-system svc/rancher 8443:443
  set {
    name  = "service.type"
    value = "ClusterIP"
  }

  # Required on k3s 1.25+ (PSP removed)
  set {
    name  = "global.cattle.pspEnabled"
    value = "false"
  }

  # Annotate the ingress so cert-manager issues a cert signed by our CA
  set {
    name  = "ingress.extraAnnotations.cert-manager\\.io/cluster-issuer"
    value = "private-ca-issuer"
  }

  wait    = true
  timeout = 600
}
